import Header from "@/components/Header";
import Main from "@/components/Main";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${lato.className} dark:bg-gray-950`}>
        <Header />
        <Main>
          <section className="prose dark:prose-invert mx-auto">{children}</section>
        </Main>
      </body>
    </html>
  );
}
